In [1]:
import numpy as np

In [2]:
np.random.randn()

-1.4567086692013302

In [3]:
np.random.randint(100)

45

In [4]:
ls=[1,2,3]

In [5]:
np.array(ls)

array([1, 2, 3])

In [6]:
ls=[[1,2,3],[4,5,6]]

In [7]:
np.array(ls)

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
for i in range(10):
    if i%2==0:
        print(np.random.randint(50))
    else:
            print(np.random.randint(50,100))

7
66
8
98
22
94
43
81
25
77


In [11]:
ls=[x for x in range(10)]
ls

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
ls= [x for x in range(10) if x%2!=0]
print(x)

NameError: name 'x' is not defined

In [13]:
x=10
y=20
x
y

20

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(10,100,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [16]:
np.arange(10,100,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [17]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [19]:
ls

[1, 3, 5, 7, 9]

In [20]:
n=np.array(ls)

In [21]:
n.shape

(5,)

In [22]:
n

array([1, 3, 5, 7, 9])

In [27]:
ls.append(6)

In [28]:
n

array([1, 3, 5, 7, 9])

In [29]:
n=np.array(ls)

In [30]:
n

array([1, 3, 5, 7, 9, 6])

In [31]:
n.shape

(6,)

In [32]:
n.reshape(2,3)

array([[1, 3, 5],
       [7, 9, 6]])

In [33]:
n.dtype

dtype('int32')

In [34]:
n[1:]

array([3, 5, 7, 9, 6])

In [35]:
n

array([1, 3, 5, 7, 9, 6])

In [36]:
n[1:3]

array([3, 5])

In [37]:
ls=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

In [38]:
mn=np.array(ls)

In [39]:
mn

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [40]:
mn[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [41]:
n

array([1, 3, 5, 7, 9, 6])

In [42]:
n>5

array([False, False, False,  True,  True,  True])

In [67]:
if n>7 and n<3;
n[n]

SyntaxError: invalid syntax (<ipython-input-67-f9e2379558f7>, line 1)

In [45]:
arr=[0,1,2]
n=np.array(arr)
n+10

array([10, 11, 12])

In [46]:
n.sum()

3

In [47]:
labels=['a','b','c']
my_data=[10,20,30]
arr= np.array(my_data)
d={'a':10,'b':20,'c':30}

In [49]:
import pandas as pd

In [50]:
pd.Series(labels)

0    a
1    b
2    c
dtype: object

In [51]:
pd.Series(index=labels,data=my_data)

a    10
b    20
c    30
dtype: int64

In [52]:
df1=pd.DataFrame(np.random.randn(6,4),['A','B','C','D','E','F'],['P','Q','R','S'])

In [53]:
df1

P         Q         R         S
A -1.657371  0.694538  1.006605 -0.759666
B  0.876948 -0.848502  0.797275  0.769210
C  0.186988 -0.938976 -0.990183  0.259195
D -0.670553 -0.352166  0.540953  1.444164
E -1.766100  1.727129  0.874344 -0.853985
F  1.569256 -2.037796 -0.864853  0.345590

In [54]:
df1.drop('A')

P         Q         R         S
B  0.876948 -0.848502  0.797275  0.769210
C  0.186988 -0.938976 -0.990183  0.259195
D -0.670553 -0.352166  0.540953  1.444164
E -1.766100  1.727129  0.874344 -0.853985
F  1.569256 -2.037796 -0.864853  0.345590

In [55]:
df1.drop('S',axis=1,inplace=True)

In [56]:
df1

P         Q         R
A -1.657371  0.694538  1.006605
B  0.876948 -0.848502  0.797275
C  0.186988 -0.938976 -0.990183
D -0.670553 -0.352166  0.540953
E -1.766100  1.727129  0.874344
F  1.569256 -2.037796 -0.864853

In [57]:
df1[df1>0]

P         Q         R
A       NaN  0.694538  1.006605
B  0.876948       NaN  0.797275
C  0.186988       NaN       NaN
D       NaN       NaN  0.540953
E       NaN  1.727129  0.874344
F  1.569256       NaN       NaN

In [58]:
df1.drop('A', inplace=True)

In [59]:
df1

P         Q         R
B  0.876948 -0.848502  0.797275
C  0.186988 -0.938976 -0.990183
D -0.670553 -0.352166  0.540953
E -1.766100  1.727129  0.874344
F  1.569256 -2.037796 -0.864853

In [60]:
df1.loc[['B','C']]

P         Q         R
B  0.876948 -0.848502  0.797275
C  0.186988 -0.938976 -0.990183

In [61]:
df1.loc['C']

P    0.186988
Q   -0.938976
R   -0.990183
Name: C, dtype: float64

In [62]:
d={'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3,]}

In [63]:
df = pd.DataFrame(d)

In [64]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [65]:
pd.read_csv('Salaries.csv',low_memory=False)

Unnamed: 0      Id            EmployeeName  \
0                0       1          NATHANIEL FORD   
1                1       2            GARY JIMENEZ   
2                2       3          ALBERT PARDINI   
3                3       4       CHRISTOPHER CHONG   
4                4       5         PATRICK GARDNER   
5                5       6          DAVID SULLIVAN   
6                6       7               ALSON LEE   
7                7       8           DAVID KUSHNER   
8                8       9          MICHAEL MORRIS   
9                9      10      JOANNE HAYES-WHITE   
10              10      11           ARTHUR KENNEY   
11              11      12        PATRICIA JACKSON   
12              12      13       EDWARD HARRINGTON   
13              13      14             JOHN MARTIN   
14              14      15          DAVID FRANKLIN   
15              15      16         RICHARD CORRIEA   
16              16      17                AMY HART   
17              17      18          SEBASTIAN WONG   
18              18      19              MARTY ROSS   
19              19      20           ELLEN MOFFATT   
20              20      21              VENUS AZAR   
21              21      22            JUDY MELINEK   
22              22      23           GEORGE GARCIA   
23              23      24           VICTOR WYRSCH   
24              24      25         JOSEPH DRISCOLL   
25              25      26            GREGORY SUHR   
26              26      27             JOHN HANLEY   
27              27      28          RAYMOND GUZMAN   
28              28      29          DENISE SCHMITT   
29              29      30           MONICA FIELDS   
...            ...     ...                     ...   
148015      148620  148621         India C Sabater   
148016      148621  148622          Kenneth Mackey   
148017      148622  148623      Jacqueline Hubbard   
148018      148623  148624         Deborah B Honig   
148019      148624  148625      Lorraine Rosenthal   
148020      148625  148626         Renato C Gurion   
148021      148626  148627           Paulet Gaines   
148022      148627  148628        Brett A Lundberg   
148023      148628  148629          Mark W Mcclure   
148024      148629  148630       Elizabeth Iniguez   
148025      148630  148631            Randy J Keys   
148026      148631  148632         Andre M Johnson   
148027      148632  148633  Sharon D Owens-Webster   
148028      148633  148634        Edward Ferdinand   
148029      148634  148635          David M Turner   
148030      148635  148636     James S Kibblewhite   
148031      148636  148637           Andrew J Enzi   
148032      148637  148638        Kadeshra D Green   
148033      148638  148639    Lennard B Hutchinson   
148034      148639  148640       Richard A Talbert   
148035      148640  148641      Charlene D Mccully   
148036      148641  148642   Raphael Marquis Goins   
148037      148642  148643       Dominic C Marquez   
148038      148643  148644              Kim Brewer   
148039      148644  148645            Randy D Winn   
148040      148645  148646        Carolyn A Wilson   
148041      148647  148648          Joann Anderson   
148042      148648  148649             Leon Walker   
148043      148649  148650           Roy I Tillery   
148044      148653  148654               Joe Lopez   

                                                JobTitle    BasePay  \
0         GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                        CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                        CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                   WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4           DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
5                              ASSISTANT DEPUTY CHIEF II  118602.00   
6                     BATTALION CHIEF, (FIRE DEPARTMENT)   92492.01   
7                         DEPUTY DIRECTOR OF INVESTMENTS  256576.96   
8                   